# TODO: move this to actionslib once stable
name: Publish to R2
# Trigger on pushes to main that modify public/
on:
  push:
    branches:
      - main
    paths:
      - 'public/**'
defaults:
  run:
    shell: bash

jobs:
    publish:
        runs-on: ubuntu-latest
        container: debian:bookworm
        steps:
            - name: Install dependencies
              run: |
                apt-get update
                apt-get install --yes git git-lfs rclone
            - uses: actions/checkout@v4
              with:
                lfs: true
            - name: Sync to R2
              env:
                RCLONE_S3_PROVIDER: "Cloudflare"
                RCLONE_S3_ACCESS_KEY_ID: ${{ secrets.TEST_R2_ACCESS_KEY_ID }}
                RCLONE_S3_SECRET_ACCESS_KEY: ${{ secrets.TEST_R2_SECRET_ACCESS_KEY }}
                RCLONE_S3_ENDPOINT: "https://${{ secrets.TEST_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com"
                BUCKET: ${{ secrets.TEST_R2_BUCKET }}
              run: |
                rclone -v sync public/ :s3,env_auth:$BUCKET/
